### ISSUE TITLE
downloaded files are empty

### ISSUE THREAD

**Issue by najmabad** [edouardswiac/python-edgar#9]

**Comment by najmabad** [comment]
I followed the README example to download quarterly files from 2017 but the resulting .tsv are empty

This is the output from running the script:

``2019-06-18 16:59:30,580 - DEBUG - downloads will be saved to /var/folders/cj/5t9m866n439_0ksfd420h62w0000gn/T/tmpt5XTt2
2019-06-18 16:59:30,580 - DEBUG - downloading files since 2017
2019-06-18 16:59:30,580 - INFO - 10 index files to retrieve
2019-06-18 16:59:30,584 - DEBUG - worker count: 12
2019-06-18 16:59:33,311 - INFO - complete
2019-06-18 16:59:33,312 - INFO - Files downloaded in /var/folders/cj/5t9m866n439_0ksfd420h62w0000gn/T/tmpt5XTt2``

But then when I run ls -lh into the folder, I get:

``total 0
-rw-r--r--@ 1 najmabader  staff     0B Jun 18 17:01 2017-QTR1.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2017-QTR2.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2017-QTR3.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2017-QTR4.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2018-QTR1.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2018-QTR2.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2018-QTR3.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2018-QTR4.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2019-QTR1.tsv
-rw-r--r--  1 najmabader  staff     0B Jun 18 17:01 2019-QTR2.tsv``

Any hints? Thanks!

**Comment by edouardswiac** [comment]
I am sorry it did not work for you. I've just pulled edgar from pip and ran it, and it worked for me.

```bash
$ ls -lh ~/edgar/
total 418960
-rw-r--r--  1 ed  staff    41M Jul 19 13:00 2018-QTR1.tsv
-rw-r--r--  1 ed  staff    33M Jul 19 13:00 2018-QTR2.tsv
-rw-r--r--  1 ed  staff    26M Jul 19 13:00 2018-QTR3.tsv
-rw-r--r--  1 ed  staff    27M Jul 19 13:00 2018-QTR4.tsv
-rw-r--r--  1 ed  staff    40M Jul 19 13:00 2019-QTR1.tsv
-rw-r--r--  1 ed  staff    33M Jul 19 13:00 2019-QTR2.tsv
-rw-r--r--  1 ed  staff   4.9M Jul 19 13:00 2019-QTR3.tsv
```

**Comment by anthrod** [comment]
I had the same issue. Turns out it works fine in Python3+ but not Python2 (at least on my machine). Using multiprocessing, I couldn't even write a simple string to the files in `_download`. Forcing it to be single threaded, `_download` then attempts to write the files but fails: 

>   File "edgar/main.py", line 103, in _download
    idxfile.write('\n'.join(lines))
TypeError: write() argument 1 must be unicode, not str

I didn't dig into it too much further since I was only using Python2 by accident, but this is something to consider at least.

Python2.7.13 on Ubuntu 16.04 btw

**Comment by edouardswiac** [comment]
Thanks @anthrod for reporting that. Let's reopen and investigate.

**Comment by edouardswiac** [comment]
@najmabad are you on python 2 as well?

**Comment by edouardswiac** [comment]
travis' python 2 jobs corroborate this https://travis-ci.org/edouardswiac/python-edgar/jobs/515963859 it's just empty.

**Comment by devferrazZz** [comment]
I had this same issue. I ran `pip install python-edgar` then created a test.py file like so:

```
import edgar
edgar.download_index('download/', 2019)
```

Using VS Code & python 2.7. Got only empty files. After some investigation it appeared that the problem was with the import. So I just copied & pasted the source code to my workfolder and ran it again. Got the files.

**Comment by edouardswiac** [comment]
I have decided to drop python 2 support in python-edgar starting v3.0.0 since the community as a whole is trying to move to python 3 https://pythonclock.org/.

**Comment by ellbosch** [comment]
I'm running into this issue on Python 3. When used as a library, no files downloaded. And if I tried to use the `run.py` it created empty files.
